export const OPEN_ORDER_MODAL = 'OPEN_ORDER_MODAL';
export const OPEN_INGRIDIENT_MODAL = 'OPEN_INGRIDIENT_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const ORDER_HAS_ERROR = 'ORDER_HAS_ERROR'